import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import { db } from '../db.js';
import * as sandbox from '../sandbox.js';
import { activePath } from './tree.js';
import { stripToolSyntax } from './history.js';
import { isTextLike, readUploadText } from './uploads.js';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

let SKILLS_CACHE = null;
export function sandboxPromptFor(chatId) {
  if (SKILLS_CACHE === null) {
    try { SKILLS_CACHE = fs.readFileSync(path.join(__dirname, '..', 'skills', 'sandbox.md'), 'utf8'); }
    catch { SKILLS_CACHE = ''; }
  }
  let p = SKILLS_CACHE;
  const env = sandbox.hostEnvInfo();
  p += `\n\n## Host environment (READ THIS BEFORE USING bash)\n- Operating system: **${env.osName}**. Shell: \`${env.shellName}\`.\n`;
  if (!env.unix) {
    p += '- This is NOT a Unix system. Commands like `cat`, `ls`, `grep`, `find`, `unzip`, `zipinfo`, `file`, `head`, `tail`, `wc`, `sed`, `awk`, `which`, `touch`, `chmod` DO NOT EXIST and will fail with exit code 9009 or "not recognized". Never call them, not even once to check.\n- For every file operation use the dedicated tools: `view`, `list_files`, `find`, `search`, `extract_zip`, `bundle_zip`, `copy_file`, `move_file`, `make_dir`, `delete_file`. They always work and are cross-platform.\n- If you need to inspect data programmatically, write a small script file with `create_file` and run it with an interpreter listed below, instead of long shell one-liners (cmd.exe quoting mangles quotes and newlines in one-liners).\n';
  } else {
    p += '- Standard Unix utilities are available, but the dedicated file tools (`view`, `list_files`, `find`, `search`, `extract_zip`, `copy_file` and friends) are still preferred for file operations because their results are structured and versioned.\n';
  }
  p += '- Your shell working directory PERSISTS across bash calls: `cd sub` now stays in effect for later commands until you `cd` elsewhere.\n';
  p += env.interpreters.length
    ? `- Interpreters detected on this host: ${env.interpreters.join(', ')}. Only invoke interpreters from this list.\n`
    : '- No language interpreters were detected on this host. Rely on the dedicated file tools; do not assume node or python exist.\n';
  p += '\n## History markers are NOT a syntax\nEarlier tool activity may appear in this conversation as compact bracketed summaries like `[used bash: ...]` or `[used view: ...]`. Those are generated by the platform AFTER a real tool call, purely to save space. Writing text like `[used view: file.txt]` yourself does NOTHING: no tool runs, and it looks broken to the user. The ONLY way to use a tool is a real function/tool call with JSON arguments. Never write `[used`, `[tool`, or imitation tool-call text in your replies.';
  const { files, hidden } = sandbox.list(chatId, { withHidden: true });
  if (!files.length && !hidden) return p + '\n\n## Current sandbox\nThe sandbox is empty.';
  const LIST_CAP = 200, INLINE_CAP = 12;
  p += '\n\n## Current sandbox files\nThese are the LATEST versions on disk. Always edit these directly, never assume older content. The version number (vN) increases each time a file changes.\n';
  for (const f of files.slice(0, LIST_CAP)) p += `- ${f.path} (v${f.v}, ${f.size} bytes)\n`;
  if (files.length > LIST_CAP) p += `- … and ${files.length - LIST_CAP} more file(s). The list is truncated to protect context, use \`list_files\`, \`search\`, or \`view\` to inspect anything not shown here.\n`;
  if (hidden) p += `\n(${hidden} file(s) inside dependency or build folders (node_modules, .venv, target, dist, and similar) and anything matched by .gitignore are hidden from this listing and from context to keep things clean. They still exist on disk and your bash commands and interpreters use them normally; pass all:true to list_files/find to see them, or reference them by exact path.)\n`;
  p += '\n## Latest file contents (a sample; use `view` for anything not shown)\n';
  let budget = 40000, inlined = 0;
  for (const f of files) {
    if (inlined >= INLINE_CAP || budget <= 0) break;
    if (f.ext === 'zip' || !sandbox.isText(f.path)) continue;
    const txt = sandbox.readText(chatId, f.path) || '';
    if (txt.length > 8000 || txt.length > budget) {
      p += `\n### ${f.path} (v${f.v}), ${f.size} bytes, too large to inline; use the view tool to read it.\n`;
      continue;
    }
    p += `\n### ${f.path} (v${f.v})\n\`\`\`${f.ext || ''}\n${txt}\n\`\`\`\n`;
    budget -= txt.length; inlined++;
  }
  p += '\n---\nREMINDER: The workspace is ON and the files above are the current truth. Edit existing files with `str_replace` (never recreate them from scratch), and use the dedicated file tools, `copy_file`, `move_file`, `make_dir`, `delete_file`, `find`, `search`, `bundle_zip`, `extract_zip`, for file operations. Use relative paths only. Keep calling tools until the task is fully done; do not stop to ask permission, do not paste whole file contents or fake terminal output into the chat, and when a tool fails, read the error and change approach instead of repeating the same call. Never write imitation tool text like `[used bash: ...]` in a reply; make real tool calls.';
  return p;
}

const BASH_TOOLS = new Set(['bash', 'run', 'shell']);

export function cleanCall(call) {
  const o = { tool: call.tool };
  if (call.path != null) o.path = call.path;
  if (BASH_TOOLS.has(call.tool)) { o.cmd = call.cmd ?? call.command ?? ''; if (call.workdir ?? call.cwd) o.workdir = call.workdir ?? call.cwd; }
  if (call.new_path != null || call.to != null) o.new_path = call.new_path ?? call.to;
  if (call.query != null) o.query = call.query;
  if (call.pattern != null) o.pattern = call.pattern;
  if (call.name != null) o.name = call.name;
  if (call.dest != null) o.dest = call.dest;
  if (call.start != null) o.start = call.start;
  if (call.end != null) o.end = call.end;
  if (call.replace_all === true || call.replace_all === 'true') o.replace_all = true;
  if (call.regex === true || call.regex === 'true') o.regex = true;
  if (call.all === true || call.all === 'true') o.all = true;
  return o;
}

export function resultPayload(call, r) {
  const o = { ok: !!r.ok };
  if (r.error) o.error = r.error;
  if (r.v != null) o.v = r.v;
  if (r.adds != null) o.adds = r.adds;
  if (r.dels != null) o.dels = r.dels;
  if (r.bytes != null) o.bytes = r.bytes;
  if (r.unchanged) o.unchanged = true;
  if (r.lines != null) o.lines = r.lines;
  if (r.count != null) o.count = r.count;
  if (r.replaced != null) o.replaced = r.replaced;
  if (r.cleared != null) o.cleared = r.cleared;
  if (r.hidden != null) o.hidden = r.hidden;
  if (r.deps != null) o.deps = r.deps;
  if (r.note) o.note = r.note;
  if (r.path != null) o.path = r.path;
  if (r.from != null) o.from = r.from;
  if (r.cwd) o.cwd = r.cwd;
  if (BASH_TOOLS.has(call.tool)) { o.output = (r.output || '').slice(0, 8000); o.exit = r.exit ?? null; }
  if ((call.tool === 'list_files' || call.tool === 'ls' || call.tool === 'tree') && Array.isArray(r.files)) o.files = r.files.slice(0, 100).map(f => ({ path: f.path, size: f.size }));
  if ((call.tool === 'find' || call.tool === 'glob') && Array.isArray(r.matches)) o.matches = r.matches.slice(0, 60);
  if (call.tool === 'extract_zip' && Array.isArray(r.files)) o.files = r.files.slice(0, 60);
  if ((call.tool === 'search' || call.tool === 'grep') && Array.isArray(r.matches)) o.matches = r.matches.slice(0, 40);
  return o;
}

export function formatToolResult(call, r) {
  const head = `${call.tool}${call.path ? ' ' + call.path : ''}`;
  if (!r.ok) return `${head} → ERROR: ${r.error}` + (r.output ? `\n${r.output}` : '');
  switch (call.tool) {
    case 'bash': case 'run': case 'shell': return `$ ${call.cmd ?? call.command ?? ''}\n${r.output || '(no output)'}\n(exit ${r.exit ?? 0}${r.cwd ? `, cwd: ${r.cwd || '.'}` : ''})`;
    case 'create_file': case 'write_file': return r.unchanged ? `${head} → unchanged (already v${r.v}, identical content, no write needed)` : `${head} → created (v${r.v}, ${r.bytes} bytes, +${r.adds ?? 0}/-${r.dels ?? 0})`;
    case 'str_replace': case 'edit_file': return `${head} → edited (now v${r.v}, +${r.adds ?? 0}/-${r.dels ?? 0}${r.replaced > 1 ? `, ${r.replaced} occurrences` : ''})`;
    case 'insert_lines': return `${head} → inserted ${r.adds} line(s) (now v${r.v})`;
    case 'view': case 'read_file': case 'cat': return `${head} →\n${r.content}`;
    case 'list_files': case 'ls': case 'tree': return `${head} →\n${r.tree || '(empty)'}` + (r.hidden ? `\n(${r.hidden} item(s) in ignored dependency/build folders hidden; pass all:true to include them)` : '');
    case 'find': case 'glob': return `find "${call.pattern ?? call.query}" → ${r.count} file(s)` + (r.matches && r.matches.length ? '\n' + r.matches.map(m => m.path).join('\n') : '');
    case 'delete_file': case 'rm': return `${head} → deleted`;
    case 'clear_sandbox': case 'delete_all': case 'reset': return `clear_sandbox → removed ${r.cleared} item(s); the directory is now empty`;
    case 'rename_file': case 'move_file': case 'mv': return `${head} → moved to ${r.path}`;
    case 'copy_file': case 'cp': return `${head} → copied to ${r.path}${r.count > 1 ? ` (${r.count} files)` : ''}`;
    case 'make_dir': case 'mkdir': return `${head} → directory ready`;
    case 'search': case 'grep': return `search "${call.query ?? call.pattern}" → ${r.count} match(es)` + (r.matches && r.matches.length ? '\n' + r.matches.map(m => `${m.path}:${m.line}: ${m.text}`).join('\n') : '');
    case 'extract_zip': case 'unzip': return `extract_zip ${call.path} → ${r.count} file(s)` + (r.note ? ` (${r.note})` : '') + (r.files && r.files.length ? ':\n' + r.files.join('\n') : '');
    case 'bundle_zip': case 'zip': return `bundle_zip ${r.path} → created (${r.count} files)`;
    default: return `${head} → ok`;
  }
}

export function runChatSearchTool(userId, currentChatId, call) {
  if (call.tool === 'chat_search') {
    const q = String(call.query || '').trim().toLowerCase();
    if (!q) return { ok: false, error: 'Empty query.' };
    const matches = [];
    const chats = db.chats.byUser(userId).sort((a, b) => (b.updated_at || 0) - (a.updated_at || 0)).slice(0, 300);
    let scanned = 0;
    for (const c of chats) {
      if (c.id === currentChatId) continue;
      if (scanned > 30000) break;
      const title = c.title || 'Untitled';
      if (title.toLowerCase().includes(q)) matches.push({ chat_id: c.id, title, date: new Date(c.updated_at || 0).toISOString().slice(0, 10), text: '(title match)' });
      if (matches.length >= 25) break;
      for (const m of db.messages.byChat(c.id)) {
        scanned++;
        const content = String(m.content || '');
        const idx = content.toLowerCase().indexOf(q);
        if (idx === -1) continue;
        const from = Math.max(0, idx - 80);
        matches.push({ chat_id: c.id, title, date: new Date(c.updated_at || 0).toISOString().slice(0, 10), role: m.role, text: content.slice(from, idx + q.length + 120).replace(/\s+/g, ' ') });
        if (matches.length >= 25) break;
      }
      if (matches.length >= 25) break;
    }
    return { ok: true, query: call.query, count: matches.length, matches };
  }
  if (call.tool === 'chat_view') {
    const c = db.chats.byId(String(call.chat_id || ''));
    if (!c || c.user_id !== userId) return { ok: false, error: 'No such chat.' };
    const limit = Math.min(60, Math.max(1, parseInt(call.limit) || 20));
    const msgs = activePath(c.id).filter(m => m.role === 'user' || m.role === 'assistant').slice(-limit)
      .map(m => ({ role: m.role, content: stripToolSyntax(String(m.content || '')).slice(0, 2000) }));
    return { ok: true, chat_id: c.id, title: c.title || 'Untitled', count: msgs.length, messages: msgs };
  }
  return { ok: false, error: 'Unknown chat tool.' };
}

export function formatChatSearchResult(call, r) {
  if (!r.ok) return `${call.tool} \u2192 ERROR: ${r.error}`;
  if (call.tool === 'chat_search') {
    return `chat_search "${call.query}" \u2192 ${r.count} match(es)` + (r.matches.length ? '\n' + r.matches.map(m => `[${m.chat_id}] ${m.title} (${m.date})${m.role ? ' ' + m.role : ''}: ${m.text}`).join('\n') : '');
  }
  return `chat_view ${r.chat_id} \u2014 ${r.title} \u2192\n` + r.messages.map(m => `${m.role}: ${m.content}`).join('\n');
}

export function chatSearchPayload(call, r) {
  const o = { ok: !!r.ok };
  if (r.error) o.error = r.error;
  if (r.count != null) o.count = r.count;
  if (r.title) o.title = r.title;
  if (call.tool === 'chat_search' && Array.isArray(r.matches)) o.matches = r.matches.slice(0, 10).map(m => ({ chat_id: m.chat_id, title: m.title }));
  return o;
}

export function endChatPromptFor(model) {
  let p = '## Ending conversations\nYou have an `end_conversation` tool. Calling it PERMANENTLY closes this chat: the user cannot reply, edit, regenerate, or branch it afterwards. When you decide to end a conversation, first clearly explain to the user in your reply why the conversation is being ended, and only then call the tool with a short `reason`. Never call it silently or without explanation, and never mention it as a threat.';
  const extra = String(model.end_chat_prompt || '').trim();
  if (extra) p += '\n\nAdditional instructions from the administrator about when to end conversations:\n' + extra;
  return p;
}

export function fmtDuration(ms) {
  const m = Math.floor(ms / 60000);
  if (m < 1) return 'under a minute';
  if (m < 60) return `${m} minute${m === 1 ? '' : 's'}`;
  const h = Math.floor(m / 60), rm = m % 60;
  if (h < 24) return `${h} hour${h === 1 ? '' : 's'}${rm ? ` ${rm} min` : ''}`;
  const d = Math.floor(h / 24);
  return `${d} day${d === 1 ? '' : 's'}${h % 24 ? ` ${h % 24} h` : ''}`;
}

export function longConvoReminderFor(chatId) {
  const msgs = activePath(chatId).filter(m => m.role === 'user' || m.role === 'assistant');
  if (!msgs.length) return '';
  const first = msgs[0].created_at || Date.now();
  const last = msgs[msgs.length - 1].created_at || Date.now();
  const nowTs = Date.now();
  const gap = nowTs - last;
  const fresh = gap < 3 * 60 * 60 * 1000;
  let p = '## Long conversation awareness\n';
  p += `This conversation started ${fmtDuration(nowTs - first)} ago (${new Date(first).toLocaleString()}). `;
  p += `It contains ${msgs.length} messages. The previous message was ${fmtDuration(gap)} ago (${new Date(last).toLocaleString()}). Current time: ${new Date(nowTs).toLocaleString()}.\n`;
  if (fresh && msgs.length >= 20) {
    p += 'This has been a long continuous session. If the moment is natural (a task just finished, a stopping point was reached), you may gently suggest the user take a short break, without being pushy or repeating the suggestion every message.';
  } else {
    p += 'Use these timestamps for temporal awareness. If the session becomes very long and continuous, you may gently suggest a short break at a natural stopping point \u2014 at most once in a while, never repeatedly.';
  }
  return p;
}

export const CHAT_SEARCH_PROMPT = "## Past conversations\nYou can search the user's other conversations in this app with `chat_search` (pass `query`) and read one with `chat_view` (pass `chat_id`). Use these when the user refers to something discussed in a previous chat instead of saying you have no memory of it.";

export function lastUserQuery(chatId) {
  const rows = activePath(chatId);
  for (let i = rows.length - 1; i >= 0; i--) if (rows[i].role === 'user' && (rows[i].content || '').trim()) return stripToolSyntax(rows[i].content);
  return '';
}

export async function pinnedFilesPrompt(chat, query) {
  const pins = Array.isArray(chat?.pinned_files) ? chat.pinned_files : [];
  if (!pins.length) return '';
  const blocks = [];
  for (const a of pins) {
    if (isTextLike(a)) blocks.push(`--- Pinned file: ${a.name} ---\n${readUploadText(a.url)}`);
    else blocks.push(`[Pinned file: ${a.name} (not readable as text)]`);
  }
  if (!blocks.length) return '';
  return 'The user has pinned the following file(s) to this conversation. Keep their contents available as context for every turn:\n\n' + blocks.join('\n\n');
}
